import { assetUrl } from "@/lib/supabase-storage";

export const PERSONAL_INFO = {
  name: "Rifqi",
  role: "Frontend Developer & Sistem Informasi Student",
  location: "Indonesia",
  email: "rfqiii1511@gmail.com",

  github: "https://github.com/ki1bot",
  linkedin:
    "https://www.linkedin.com/in/rifq1?utm_source=share_via&utm_content=profile&utm_medium=member_android",
  instagram: "https://www.instagram.com/ki1bot_?igsh=M3o2OTdvb2Q1eXI1",
  spotify:
    "https://open.spotify.com/user/314fig6hgrc2gaq7phryrrmfcp34?si=45c2f5e0cf9e4291",
  youtube: "https://www.youtube.com/@kibot7659",
  tiktok: "https://www.tiktok.com/@kiibott_?_r=1&_t=ZS-96Aalc9CrbQ",

  profileImage: assetUrl("assets/default-avatar.jpg"),
  description:
    "Saya membangun website modern, responsif, dan terstruktur menggunakan React, Next.js, Tailwind CSS, Shadcn, dan Supabase.",
};

export const TECH_STACK = [
  { name: "HTML", icon: assetUrl("techstack/html.svg") },
  { name: "CSS", icon: assetUrl("techstack/css.svg") },
  { name: "JavaScript", icon: assetUrl("techstack/javascript.svg") },
  { name: "TypeScript", icon: assetUrl("techstack/typescript.png") },
  { name: "Tailwind CSS", icon: assetUrl("techstack/tailwind.svg") },
  { name: "Bootstrap", icon: assetUrl("techstack/bootstrap.svg") },
  { name: "Node.js", icon: assetUrl("techstack/nodejs.svg") },
  { name: "Vite", icon: assetUrl("techstack/vite.svg") },
  { name: "React", icon: assetUrl("techstack/reactjs.svg") },
  { name: "Next.js", icon: assetUrl("techstack/nextjs.png") },
  { name: "NestJS", icon: assetUrl("techstack/nestjs.png") },
  { name: "Express.js", icon: assetUrl("techstack/expressjs.png") },
  { name: "PHP", icon: assetUrl("techstack/php.png") },
  { name: "Laravel", icon: assetUrl("techstack/laravel.png") },
  { name: "Java", icon: assetUrl("techstack/java.png") },
  { name: "Dart", icon: assetUrl("techstack/dart.png") },
  { name: "Flutter", icon: assetUrl("techstack/flutter.png") },
  { name: "Golang", icon: assetUrl("techstack/golang.png") },
  { name: "Python", icon: assetUrl("techstack/python.png") },
  { name: "C++", icon: assetUrl("techstack/c++.png") },
  { name: "Firebase", icon: assetUrl("techstack/firebase.svg") },
  { name: "Supabase", icon: assetUrl("techstack/supabase.png") },
  { name: "MySQL", icon: assetUrl("techstack/mysql.png") },
  { name: "PostgreSQL", icon: assetUrl("techstack/postgresql.png") },
  { name: "MongoDB", icon: assetUrl("techstack/mongodb.png") },
  { name: "Prisma", icon: assetUrl("techstack/prismaorm.png") },
  { name: "Docker", icon: assetUrl("techstack/docker.png") },
  { name: "Vercel", icon: assetUrl("techstack/vercel.svg") },
  { name: "Figma", icon: assetUrl("techstack/figma.png") },
  { name: "Linux", icon: assetUrl("techstack/linux.png") },
];

export const FALLBACK_PROJECTS = [
  {
    id: 1,
    title: "Sistem Marketplace Broker",
    description:
      "Dashboard sistem marketplace broker yang dibangun menggunakan Laravel 12 sebagai backend, ReactJS sebagai frontend, dan MySQL sebagai database. Sistem ini digunakan untuk mengelola broker, seller, buyer, produk, transaksi, negosiasi, komisi, dan riwayat transaksi dalam satu tampilan modern.",
    img: assetUrl("projects/MarketPlaceBroker.png"),
    link: "https://sistemmarketplacebroker.vercel.app/",
    github: "https://github.com/ki1bot/sistem-marketplace-broker.git",
    features: [
      "Frontend menggunakan ReactJS, Backend menggunakan Laravel 12 dan Database menggunakan MySQL",
      "Dashboard utama dan Manajemen broker",
      "Manajemen seller, buyer dan Data produk marketplace",
      "Transaksi, Negosiasi dan Riwayat transaksi",
      "Komisi broker, Visualisasi grafik produk dan status transaksi",
    ],
    tech_stack: [
      "Laravel 12",
      "ReactJS",
      "MySQL",
      "JavaScript",
      "Tailwind CSS",
    ],
    is_published: true,
    order_index: 1,
  },
  {
    id: 2,
    title: "Yayasan Azzahra-Perwira",
    description:
      "Website yayasan dengan halaman publik dan dashboard admin untuk mengelola konten lembaga. Project ini dibuat menggunakan CodeIgniter 4, PHP, MySQL, CSS, dan JavaScript, dengan fitur pengelolaan halaman seperti beranda, profil, tenaga pengajar, unit KB/TK, TPQ, daycare, lansia, dan informasi.",
    img: assetUrl("projects/adminUiYayasan.png"),
    link: "https://localhost/azzahra-perwira",
    github: "https://github.com/ki1bot/project-yayasanV5.git",
    features: [
      "Dashboard admin untuk mengelola konten website yayasan",
      "Manajemen halaman Beranda, Profile, Tenaga Pengajar, Unit KB/TK, Unit TPQ, Unit Daycare, Unit Lansia, dan Informasi",
      "Sistem login admin untuk membatasi akses pengelolaan konten",
      "Pengelolaan konten teks dan gambar dari satu panel admin",
      "Backend menggunakan CodeIgniter 4 dan PHP dengan database MySQL",
    ],
    tech_stack: ["CodeIgniter 4", "PHP", "MySQL", "JavaScript", "CSS"],
    is_published: true,
    order_index: 2,
  },
  {
    id: 3,
    title: "QR Code Generator",
    description:
      "Aplikasi web generate QR Code yang dibuat menggunakan React, TypeScript, Vite, Tailwind CSS, dan qrcode.react. Project ini mendukung pembuatan QR Code untuk URL, domain, Gmail, WhatsApp, telepon, SMS, dan teks biasa. Aplikasi juga dilengkapi fitur tema terang dan gelap, custom warna QR Code, preview real-time, copy target output, serta download QR Code dalam format PNG.",
    img: assetUrl("projects/ProjectQrcode.png"),
    link: "https://generate-qrcode-one.vercel.app/",
    github: "https://github.com/ki1bot/generate-qrcode.git",
    features: [
      "Generate QR Code secara real-time dari input user",
      "Mendukung URL, domain, Gmail, WhatsApp, telepon, SMS, dan teks biasa",
      "Teks biasa otomatis diarahkan ke halaman browser yang menampilkan teks tersebut",
      "Custom warna QR Code dan warna background QR Code",
      "Fitur download QR Code sebagai PNG dan copy target output",
      "Tema terang dan tema gelap dengan tombol icon sun dan moon",
      "Responsive untuk desktop dan mobile",
    ],
    tech_stack: [
      "Vite",
      "React",
      "JavaScript",
      "TypeScript",
      "Tailwind CSS",
      "qrcode.react",
    ],
    is_published: true,
    order_index: 3,
  },
];

export const FALLBACK_CERTIFICATES = [
  {
    id: 1,
    title: "Dicoding Certificate 1",
    img: assetUrl("sertifikat/dicoding1.png"),
    pdf_url: assetUrl("sertifikat/dicoding1.pdf"),
    type: "pdf",
    order_index: 1,
  },
  {
    id: 2,
    title: "Dicoding Certificate 2",
    img: assetUrl("sertifikat/dicoding2.png"),
    pdf_url: assetUrl("sertifikat/dicoding2.pdf"),
    type: "pdf",
    order_index: 2,
  },
  {
    id: 3,
    title: "Dicoding Certificate 3",
    img: assetUrl("sertifikat/dicoding3.png"),
    pdf_url: assetUrl("sertifikat/dicoding3.pdf"),
    type: "pdf",
    order_index: 3,
  },
  {
    id: 4,
    title: "Dicoding Certificate 4",
    img: assetUrl("sertifikat/dicoding4.png"),
    pdf_url: assetUrl("sertifikat/dicoding4.pdf"),
    type: "pdf",
    order_index: 4,
  },
  {
    id: 5,
    title: "Dicoding Certificate 5",
    img: assetUrl("sertifikat/dicoding5.png"),
    pdf_url: assetUrl("sertifikat/dicoding5.pdf"),
    type: "pdf",
    order_index: 5,
  },
  {
    id: 6,
    title: "Dicoding Certificate 6",
    img: assetUrl("sertifikat/dicoding6.png"),
    pdf_url: assetUrl("sertifikat/dicoding6.pdf"),
    type: "pdf",
    order_index: 6,
  },
  {
    id: 7,
    title: "Dicoding Certificate 7",
    img: assetUrl("sertifikat/dicoding7.png"),
    pdf_url: assetUrl("sertifikat/dicoding7.pdf"),
    type: "pdf",
    order_index: 7,
  },
  {
    id: 8,
    title: "Dicoding Certificate 8",
    img: assetUrl("sertifikat/dicoding8.png"),
    pdf_url: assetUrl("sertifikat/dicoding8.pdf"),
    type: "pdf",
    order_index: 8,
  },
  {
    id: 9,
    title: "Dicoding Certificate 9",
    img: assetUrl("sertifikat/dicoding9.png"),
    pdf_url: assetUrl("sertifikat/dicoding9.pdf"),
    type: "pdf",
    order_index: 9,
  },
  {
    id: 10,
    title: "Sertifikat LSP Semester 1",
    img: assetUrl("sertifikat/sertifikatlsp-semester1.png"),
    pdf_url: assetUrl("sertifikat/sertifikatlsp-semester1.pdf"),
    type: "pdf",
    order_index: 10,
  },
  {
    id: 11,
    title: "Sertifikat LSP Semester 2",
    img: assetUrl("sertifikat/sertifikatlsp-semester2.png"),
    pdf_url: assetUrl("sertifikat/sertifikatlsp-semester2.pdf"),
    type: "pdf",
    order_index: 11,
  },
  {
    id: 12,
    title: "Sertifikat Kompetensi",
    img: assetUrl("sertifikat/SertifikatKompetensi.png"),
    pdf_url: assetUrl("sertifikat/SertifikatKompetensi.pdf"),
    type: "pdf",
    order_index: 12,
  },
];

export const FALLBACK_COMMENTS = [
  {
    id: "fallback-pinned-comment",
    user_name: "Rifqi",
    content: "Halo, terima kasih sudah mampir ke portofolio saya.",
    profile_image: assetUrl("assets/default-avatar.jpg"),
    is_pinned: true,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "fallback-guest-comment",
    user_name: "Guest",
    content: "Portofolionya rapi, modern, dan mudah dipahami.",
    profile_image: assetUrl("assets/default-avatar.jpg"),
    is_pinned: false,
    created_at: "2026-01-02T00:00:00.000Z",
  },
];
